function createfigure(X1, Y1, Z1, S1, C1, XMatrix1, YMatrix1, ZMatrix1)
%CREATEFIGURE(X1, Y1, Z1, S1, C1, XMATRIX1, YMATRIX1, ZMATRIX1)
%  X1:  scatter3 x
%  Y1:  scatter3 y
%  Z1:  scatter3 z
%  S1:  scatter3 s
%  C1:  scatter3 c
%  XMATRIX1:  matrix of x data
%  YMATRIX1:  matrix of y data
%  ZMATRIX1:  matrix of z data

%  Auto-generated by MATLAB on 24-Sep-2017 02:40:39

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(1,2,1,'Parent',figure1);
hold(subplot1,'on');

% Create scatter3
scatter3(X1,Y1,Z1,S1,C1,'Parent',subplot1);

% Create multiple lines using matrix input to plot3
plot31 = plot3(XMatrix1,YMatrix1,ZMatrix1,'Parent',subplot1,'LineWidth',1.5);
set(plot31(1),'Color',[1 1 0]);
set(plot31(2),'Color',[0 1 0]);
set(plot31(3),'Color',[0 0 1]);
set(plot31(4),'Color',[1 0 0]);

view(subplot1,[-170.92 88.3846484375]);
grid(subplot1,'on');
axis(subplot1,'square');
% Create subplot
subplot2 = subplot(1,2,2,'Parent',figure1);
hold(subplot2,'on');

% Create multiple lines using matrix input to plot3
plot32 = plot3(XMatrix1,YMatrix1,ZMatrix1,'Parent',subplot2);
set(plot32(1),'Color',[1 1 0]);
set(plot32(2),'Color',[0 1 0]);
set(plot32(3),'Color',[0 0 1]);
set(plot32(4),'Color',[1 0 0]);

% Create text
text('Parent',subplot2,'String','(1,-1,0)','Position',[0 0 85]);

% Create text
text('Parent',subplot2,'String','(1,1,-2)','Position',[85 0 0]);

% Create text
text('Parent',subplot2,'String','(1,1,1)','Position',[0 85 0]);

box(subplot2,'on');
axis(subplot2,'square');
% Set the remaining axes properties
set(subplot2,'CameraPosition',...
    [-6.16387105377906 38.568199011593 3462.72517383223],'CameraUpVector',...
    [0 0 1]);
